#!/usr/bin/with-contenv bash

# create our folders
mkdir -p \
	/config/{data,logs,run}

# create symlinks for config
[[ -L /usr/lib/unifi/data && ! /usr/lib/unifi/data -ef /config/data ]] && unlink /usr/lib/unifi/data
[[ -L /usr/lib/unifi/logs && ! /usr/lib/unifi/logs -ef /config/logs ]] && unlink /usr/lib/unifi/logs
[[ -L /usr/lib/unifi/run && ! /usr/lib/unifi/run -ef /config/run ]] && unlink /usr/lib/unifi/run
[[ ! -L /usr/lib/unifi/data ]] && ln -s /config/data /usr/lib/unifi/data
[[ ! -L /usr/lib/unifi/logs ]] && ln -s /config/logs /usr/lib/unifi/logs
[[ ! -L /usr/lib/unifi/run ]] && ln -s /config/run /usr/lib/unifi/run

# fix non-loading webui
if [ ! -f "/config/data/system.properties" ]; then
echo "unifi.https.ciphers=TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA" >> /config/data/system.properties
echo "unifi.https.sslEnabledProtocols=TLSv1.2" >> /config/data/system.properties
chown abc:abc /config/data/system.properties
chmod 600 /config/data/system.properties
fi

# permissions
chown -R abc:abc \
	/config \
	/usr/lib/unifi
