#!/usr/bin/with-contenv bash

# create our folders
mkdir -p \
	/config/{data,logs,run}


# create symlinks for config
symlinks=( \
/usr/lib/unifi/data \
/usr/lib/unifi/logs \
/usr/lib/unifi/run )

for i in "${symlinks[@]}"
do
[[ -L "$i" && ! "$i" -ef /config/"$(basename "$i")"  ]] && unlink "$i"
[[ ! -L "$i" ]] && ln -s /config/"$(basename "$i")" "$i"
done

# fix non-loading webui
if [ ! -f "/config/data/system.properties" ]; then
echo "unifi.https.ciphers=TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA" >> /config/data/system.properties
echo "unifi.https.sslEnabledProtocols=TLSv1.2" >> /config/data/system.properties
chown abc:abc /config/data/system.properties
chmod 600 /config/data/system.properties
fi

# permissions
chown -R abc:abc \
	/config \
	/usr/lib/unifi
